export const LOAD_ALL: string = 'LOAD_ALL'
export const CHANGE_VALUE: string = 'CHANGE_VALUE'
export const LOAD_MORE: string = 'LOAD_MORE'
export const CLOSE_STAT: string = 'CLOSE_STAT'
export const LOAD_CHANGE: string = 'LOAD_CHANGE'
